create table if not exists public.events (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  session_id text not null,
  event_name text not null,
  event_target text,
  page_path text,
  milliseconds_since_first_visit bigint,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists events_visitor_id_idx on public.events(visitor_id);
create index if not exists events_session_id_idx on public.events(session_id);
create index if not exists events_event_name_idx on public.events(event_name);
create index if not exists events_created_at_idx on public.events(created_at);

create table if not exists public.leads (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  session_id text not null,
  name text,
  email text,
  target_role text,
  current_blocker text,
  profile_url text,
  pain_point text,
  price_choice text,
  milliseconds_to_submit bigint,
  first_touch jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

create index if not exists leads_visitor_id_idx on public.leads(visitor_id);
create index if not exists leads_email_idx on public.leads(email);
create index if not exists leads_created_at_idx on public.leads(created_at);

alter table public.events enable row level security;
alter table public.leads enable row level security;

drop policy if exists "Allow anonymous insert events" on public.events;
create policy "Allow anonymous insert events"
on public.events for insert
to anon
with check (true);

drop policy if exists "Allow anonymous insert leads" on public.leads;
create policy "Allow anonymous insert leads"
on public.leads for insert
to anon
with check (true);
